#!/bin/bash
# One-time, per Mac: create a self-signed code-signing certificate so macOS keeps
# TrayFold's Accessibility permission across rebuilds. Safe to re-run.
# macOS asks for your login password once, to trust the certificate.
set -euo pipefail

NAME="TrayFold Local Signing"
KEYCHAIN="$HOME/Library/Keychains/login.keychain-db"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOCAL="$ROOT/Config/Signing.local.xcconfig"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if ! security find-certificate -c "$NAME" "$KEYCHAIN" >/dev/null 2>&1; then
  echo "Creating certificate \"$NAME\"…"
  # /usr/bin/openssl is LibreSSL; its PKCS#12 output imports as-is (no -legacy).
  /usr/bin/openssl req -x509 -newkey rsa:2048 -days 3650 -nodes \
    -keyout "$TMP/key.pem" -out "$TMP/cert.pem" -subj "/CN=$NAME" \
    -addext "keyUsage=critical,digitalSignature" \
    -addext "extendedKeyUsage=codeSigning" 2>/dev/null
  /usr/bin/openssl pkcs12 -export -in "$TMP/cert.pem" -inkey "$TMP/key.pem" \
    -out "$TMP/identity.p12" -password pass:trayfold
  # -T lets codesign use the private key without a keychain prompt on every build.
  security import "$TMP/identity.p12" -k "$KEYCHAIN" -P trayfold -T /usr/bin/codesign
fi

if ! security find-identity -v -p codesigning "$KEYCHAIN" | grep -q "\"$NAME\""; then
  echo "Trusting \"$NAME\" for code signing (macOS will ask for your password)…"
  security find-certificate -c "$NAME" -p "$KEYCHAIN" > "$TMP/trust.pem"
  security add-trusted-cert -r trustRoot -p codeSign -k "$KEYCHAIN" "$TMP/trust.pem"
fi

printf '// Generated by Scripts/setup-signing.sh. Not committed.\nTRAYFOLD_SIGN_IDENTITY = %s\n' "$NAME" > "$LOCAL"
echo "Done. Builds on this Mac now sign as:"
security find-identity -v -p codesigning "$KEYCHAIN" | grep "$NAME"
